version: '2'

services:
    php:
        build:
          context: ./docker/php
          dockerfile: Dockerfile-7.2
        expose:
            - "9000"
        depends_on:
            - database
        volumes:
            - ./:/var/www/stockito
            - ./www.conf:/etc/php/7.2/fpm/pool.d/www.conf
    nginx:
        image: nginx:latest
        ports:
            - "8888:9999"
        links:
            - php
        depends_on:
            - php
        volumes_from:
            - php
        volumes:
            - ./:/var/www/stockito
            - ./storage/app:/var/www/stockito/storage/app
            - ./storage/logs:/var/www/stockito/storage/logs
            - ./site.conf:/etc/nginx/conf.d/site.conf
            - ./storage/logs/nginx/:/var/log/nginx
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    database:
        image: mysql:5.7
        restart: always
        environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
          - MYSQL_USER=${DB_DATABASE}
          - MYSQL_PASSWORD=${DB_DATABASE}
        ports:
            - "8989:3306"
        volumes:
            - "./docker/tmp/mysql:/var/lib/mysql"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        depends_on:
          - database
        environment:
          - PMA_HOST=database
